# Generated by Django 2.0.7 on 2018-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20180723_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateField(auto_now=True, verbose_name='date posted'),
        ),
    ]
